FROM node:22.6.0-alpine AS base
 
RUN apk add --no-cache libc6-compat 
WORKDIR /app 
 
# Install dependencies based on the preferred package manager 
COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./ 
RUN \ 
  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \ 
  elif [ -f package-lock.json ]; then npm ci; \ 
  elif [ -f pnpm-lock.yaml ]; then npm i -g pnpm && pnpm i --frozen-lockfile; \ 
  else echo "Lockfile not found." && exit 1; \ 
  fi 
 
COPY . . 

ENV NEXT_TELEMETRY_DISABLED=1
 
CMD \ 
  if [ -f yarn.lock ]; then yarn dev; \ 
  elif [ -f package-lock.json ]; then npm run dev; \ 
  elif [ -f pnpm-lock.yaml ]; then pnpm dev; \ 
  fi