# cd .ssh
# ssh-keygen -t ed25519 -f "/root/.ssh/github-actions" -C "github-actions"
# Add generated .pub to auth keys
# nano authorized_keys
# Add private key to GitHub repo secrets - $SSH_PRIVATE_KEY

# PM2
# pm2 start npm --name 2block -- start --port=3000
# pm2 save
# pm2 startup
# create .next folder in project root
# create .env (github actions should create or replace it)
# npm i or pnpm install?

# allow port 5432 on hetzner firewall

# If using NVM to manage node versions
# sudo ln -s "$NVM_DIR/versions/node/$(nvm version)/bin/node" "/usr/local/bin/node"
# sudo ln -s "$NVM_DIR/versions/node/$(nvm version)/bin/npm" "/usr/local/bin/npm"

# npm install -g pnpm
# sudo ln -s "$NVM_DIR/versions/node/$(nvm version)/bin/pnpm" "/usr/local/bin/pnpm"
# sudo ln -s "$NVM_DIR/versions/node/$(nvm version)/bin/pm2" "/usr/local/bin/pm2"

name: Build and Deploy Next.js App

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    # runs-on: self-hosted
    strategy:
      matrix:
        node-version: [v20.x]
    env:
      SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
      ENV_PROD: ${{secrets.ENV_PROD}}
      USER: root
      HOST: "5.78.42.187"
      APP_DIR: "/root/SaaS/.next"
      PM2_APP_NAME: "2block"
    steps:
      - name: Deploy to server
        run: |
          ssh vps "cd $APP_DIR && rm .env && touch .env"
          ssh vps "cd $APP_DIR echo $ENV_PROD > .env"